SECURITY_TYPE_DF = 'FORWARD'
SECURITY_TYPE_OS_DF = "ONSHORE FORWARD"
SECURITY_TYPE_NDF = "NON-DELIVERABLE FORWARD"
SECURITY_TYPE_SPOT = 'SPOT'
SECURITY_TYPE_NDIR = 'NON-DELIVERABLE IRS SWAP'
SECURITY_TYPE_CD = 'CD'
SECURITY_TYPE_SWAP = 'SWAP'