function sub_symbol_pool = get_index_pool(index_pool,t_str)
    sub_t = fetchmysql(sprintf(['select tradingdate from yuqerdata.IdxCloseWeightGet ',...
        'where tradingdate < ''%s'' and ticker = ''%s'' order by tradingdate desc limit 1'],...
                    t_str,index_pool),2);
    if isempty(sub_t)
        sub_t = fetchmysql(sprintf(['select tradingdate from yuqerdata.IdxCloseWeightGet ',...
            'where tradingdate >= ''%s'' and ticker = ''%s''  order by tradingdate limit 1'],...
        t_str,index_pool),2);
    end
    sub_symbol_pool = fetchmysql(sprintf(['select symbol from yuqerdata.IdxCloseWeightGet ',...
        'where tradingdate = ''%s'' and ticker = ''%s'''],sub_t{1},index_pool),2);
end